name: Python
on: [push, pull_request]

jobs:
  lint_and_format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"
      - name: run ruff
        run: |
          uv run ruff check pyaoc
          uv run ruff format --check pyaoc
  type_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.2"
      - name: run mypy
        run: uv run mypy --install-types pyaoc --exclude solutions
